apiVersion: v1
kind: Service
metadata:
  name: flasklinuxservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapplinux
  type: LoadBalancer
  # loadBalancerIP: 10.240.0.25  