apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: www.cdlapp.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: flasklinuxservice
                port:
                  number: 80
            path: /